apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: saraha-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: saraha-account
    namespace: devops
roleRef:
  kind: Role
  name: saraha-role
  apiGroup: rbac.authorization.k8s.io

