apiVersion: v1
kind: Service
metadata:
  name: mongo-service-headless
  namespace: devops
  labels:
    db: mongodb
spec:
  selector:
    app: appmongodb
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None

